graph TD
  User1(("User 1"))
  User2(("User 2"))
  User3(("User 3"))
  admin(("admin"))
  Frontend1["Frontend 1"]
  Frontend2["Frontend 2"]
  Database1["Database 1"]
  User1 --> Frontend1
  User1 --> Frontend2
  User2 --> Frontend1
  User3 --> Frontend1
  admin --> Database1
  Frontend2 --> Database1
