import type { IModality } from './IModality';

export interface DelegationParams {
  /** The primary task or instruction for the sub-agent */
  task: string;
  /** Suggested agent profile (e.g., 'visual-engineer', 'spec-writer') */
  agentProfile?: string;
  /** List of MCP servers that should be made available to the sub-agent */
  mcpServers?: string[];
  /** Specific skills to inject into the sub-agent's prompt */
  skills?: string[];
  /** Contextual data or file paths relevant to the task */
  context?: Record<string, unknown>;
}

export interface AgentSession {
  /** Unique ID for the delegated session */
  sessionId: string;
  /** Current status of the delegated task */
  status: 'pending' | 'active' | 'completed' | 'failed';
  /** Stream of messages from the sub-agent */
  messages: unknown[]; // To be typed with IAgentMessage
}

export interface DelegationResult {
  /** Final output or artifact generated by the sub-agent */
  output: string;
  /** Any artifacts (files, sketches) created during the session */
  artifacts?: string[];
  /** Feedback or follow-up actions suggested by the sub-agent */
  metadata?: Record<string, unknown>;
}

export interface IAgentDelegatorState {
  activeSessions: AgentSession[];
}

/**
 * The IAgentDelegator is a core system modality that manages 
 * the lifecycle of specialized sub-agents.
 */
export interface IAgentDelegator extends IModality<IAgentDelegatorState> {
  /** Dynamically spawns a specialized sub-agent for a specific task */
  spawn(params: DelegationParams): Promise<AgentSession>;
  
  /** 
   * Dynamically adds or removes tools/capabilities during an active session.
   * Useful for "just-in-time" tool authorization.
   */
  hotplug(sessionId: string, toolset: string[]): Promise<void>;
  
  /** Retrieves the final synthesis of the sub-agent's work */
  synthesize(sessionId: string): Promise<DelegationResult>;
  
  /** Terminates a delegated session and cleans up sub-agent context */
  terminate(sessionId: string): Promise<void>;
}
